// 
package org.mungo.entity;
// Generated 2015-9-14 15:53:31 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.BatchSize;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *  generated by hbm2java
 */
@Entity
@Table(name="BIS_BATCH_IMPORT_INFO"
    ,schema="POWERDESK"
)
public class BisBatchImportInfo  implements java.io.Serializable {


     private String bisBatchImportInfoId;
     private String bisBatchImportName;
     private String bisBatchImportType;
     private String bisProjectId;
     private String status;
     private String isDelete;
     private String creator;
     private String createdCenterCd;
     private String createdDeptCd;
     private String createdPositionCd;
     private Date createdDate;
     private String updator;
     private String updatedCenterCd;
     private String updatedDeptCd;
     private String updatedPositionCd;
     private Date updatedDate;
     private long recordVersion;
     private List<BisBatchImportDetail> bisBatchImportDetails = new ArrayList<BisBatchImportDetail>();

    public BisBatchImportInfo() {
    }

	
    public BisBatchImportInfo(String bisBatchImportInfoId, long recordVersion) {
        this.bisBatchImportInfoId = bisBatchImportInfoId;
        this.recordVersion = recordVersion;
    }
    public BisBatchImportInfo(String bisBatchImportInfoId, String bisBatchImportName, String bisBatchImportType, String bisProjectId, String status, String isDelete, String creator, String createdCenterCd, String createdDeptCd, String createdPositionCd, Date createdDate, String updator, String updatedCenterCd, String updatedDeptCd, String updatedPositionCd, Date updatedDate, long recordVersion, List<BisBatchImportDetail> bisBatchImportDetails) {
       this.bisBatchImportInfoId = bisBatchImportInfoId;
       this.bisBatchImportName = bisBatchImportName;
       this.bisBatchImportType = bisBatchImportType;
       this.bisProjectId = bisProjectId;
       this.status = status;
       this.isDelete = isDelete;
       this.creator = creator;
       this.createdCenterCd = createdCenterCd;
       this.createdDeptCd = createdDeptCd;
       this.createdPositionCd = createdPositionCd;
       this.createdDate = createdDate;
       this.updator = updator;
       this.updatedCenterCd = updatedCenterCd;
       this.updatedDeptCd = updatedDeptCd;
       this.updatedPositionCd = updatedPositionCd;
       this.updatedDate = updatedDate;
       this.recordVersion = recordVersion;
       this.bisBatchImportDetails = bisBatchImportDetails;
    }
   
     @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex") 
    
    @Column(name="BIS_BATCH_IMPORT_INFO_ID", unique=true, nullable=false, length=50)
    public String getBisBatchImportInfoId() {
        return this.bisBatchImportInfoId;
    }
    
    public void setBisBatchImportInfoId(String bisBatchImportInfoId) {
        this.bisBatchImportInfoId = bisBatchImportInfoId;
    }
    
    @Column(name="BIS_BATCH_IMPORT_NAME", length=200)
    public String getBisBatchImportName() {
        return this.bisBatchImportName;
    }
    
    public void setBisBatchImportName(String bisBatchImportName) {
        this.bisBatchImportName = bisBatchImportName;
    }
    
    @Column(name="BIS_BATCH_IMPORT_TYPE", length=50)
    public String getBisBatchImportType() {
        return this.bisBatchImportType;
    }
    
    public void setBisBatchImportType(String bisBatchImportType) {
        this.bisBatchImportType = bisBatchImportType;
    }
    
    @Column(name="BIS_PROJECT_ID", length=50)
    public String getBisProjectId() {
        return this.bisProjectId;
    }
    
    public void setBisProjectId(String bisProjectId) {
        this.bisProjectId = bisProjectId;
    }
    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="IS_DELETE", length=1)
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    
    @Column(name="CREATOR", length=20)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    
    @Column(name="CREATED_CENTER_CD", length=20)
    public String getCreatedCenterCd() {
        return this.createdCenterCd;
    }
    
    public void setCreatedCenterCd(String createdCenterCd) {
        this.createdCenterCd = createdCenterCd;
    }
    
    @Column(name="CREATED_DEPT_CD", length=20)
    public String getCreatedDeptCd() {
        return this.createdDeptCd;
    }
    
    public void setCreatedDeptCd(String createdDeptCd) {
        this.createdDeptCd = createdDeptCd;
    }
    
    @Column(name="CREATED_POSITION_CD", length=20)
    public String getCreatedPositionCd() {
        return this.createdPositionCd;
    }
    
    public void setCreatedPositionCd(String createdPositionCd) {
        this.createdPositionCd = createdPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATOR", length=20)
    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }
    
    @Column(name="UPDATED_CENTER_CD", length=20)
    public String getUpdatedCenterCd() {
        return this.updatedCenterCd;
    }
    
    public void setUpdatedCenterCd(String updatedCenterCd) {
        this.updatedCenterCd = updatedCenterCd;
    }
    
    @Column(name="UPDATED_DEPT_CD", length=20)
    public String getUpdatedDeptCd() {
        return this.updatedDeptCd;
    }
    
    public void setUpdatedDeptCd(String updatedDeptCd) {
        this.updatedDeptCd = updatedDeptCd;
    }
    
    @Column(name="UPDATED_POSITION_CD", length=20)
    public String getUpdatedPositionCd() {
        return this.updatedPositionCd;
    }
    
    public void setUpdatedPositionCd(String updatedPositionCd) {
        this.updatedPositionCd = updatedPositionCd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=7)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="RECORD_VERSION", nullable=false, precision=10, scale=0)
    @Version 
    public long getRecordVersion() {
        return this.recordVersion;
    }
    
    public void setRecordVersion(long recordVersion) {
        this.recordVersion = recordVersion;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="bisBatchImportInfo")
    @BatchSize(size=10)
public List<BisBatchImportDetail> getBisBatchImportDetails() {
        return this.bisBatchImportDetails;
    }
    
    public void setBisBatchImportDetails(List<BisBatchImportDetail> bisBatchImportDetails) {
        this.bisBatchImportDetails = bisBatchImportDetails;
    }




}


